[book]
authors = ["Arthur Paulino, Damiano Testa, Edward Ayers, Evgenia Karunus, Henrik Böving, Jannis Limperg, Siddhartha Gadgil, Siddharth Bhat"]
language = "ja"
multilingual = false
src = "md"
title = "Metaprogramming in Lean 4 日本語訳"

[output.html]
git-repository-url = "https://github.com/lean-ja/lean4-metaprogramming-book-ja"